gin = {
    GAMEVIEW_WIDTH = 320,
    GAMEVIEW_HEIGHT = 240,

    TILE_PIXELS = 16,
    CHUNK_TILES = 32,
    CHUNK_PIXELS = 512,
    WORLD_CHUNKS = 100,
    WORLD_PIXELS = 51200,

    init = function() end,
    update = function() end,

    on_game_load = function() end,
    on_input = function(key, pad) end,

    pause_game = function() end,
    resume_game = function() end,
    spawn_entity = function(archetype, tx, ty) return {} end,
    reap_entity = function(eid) end,

    set_sprite_animation = function(eid, anim_key) end,

    gfx = {
        get_window_title = function() return '' end,
        set_window_title = function(title) end,
        get_window_width = function() return 0 end,
        get_window_height = function() return 0 end,
        resize_window = function(w, h) end,
        get_vsync = function() return false end,
        set_vsync = function(on) end,
    },
    mix = {
        MIN_VOL = 0,
        MAX_VOL = 100,
        play_sfx = function(path) end,
        play_bgm = function(path) end,
        pause_bgm = function() end,
        resume_bgm = function() end,
        stop_bgm = function() end,
        get_master_vol = function() return 0 end,
        get_sfx_vol = function() return 0 end,
        get_bgm_vol = function() return 0 end,
        set_master_vol = function(vol) end,
        set_sfx_vol = function(vol) end,
        set_bgm_vol = function(vol) end,
        mute = function() end,
        unmute = function() end,
        toggle_mute = function() end,
    },
    gui = {
        toggle_pause = function() end,
        toggle_overmap = function() end,
    },
    io = {
        KEYBOARD = {
            KeyTab = 9,
            KeyEsc = 27,
            KeySpace = 32,
            KeyA = 97,
            KeyD = 100,
            KeyE = 101,
            KeyF = 102,
            KeyM = 109,
            KeyN = 110,
            KeyO = 111,
            KeyP = 112,
            KeyS = 115,
            KeyW = 119,
        },
        GAMEPAD = {
            BtnA = 0,
            BtnB = 1,
            BtnX = 2,
            BtnY = 3,
            BtnBack = 4,
            BtnGuide = 5,
            BtnStart = 6,
            BtnLeftStick = 7,
            BtnRightStick = 8,
            BtnLeftShldr = 9,
            BtnRightShldr = 10,
            DpadUp = 11,
            DpadDown = 12,
            DpadLeft = 13,
            DpadRight = 14,
        },
        key_down = function(key, is_repeat) end,
        key_up = function(key) end,
        pad_down = function(btn, is_repeat) end,
        pad_up = function (btn) end
    }
}
